version: '3'
services:
  spark-master:
    build: .
    image: local/spark-2
    command: spark-class org.apache.spark.deploy.master.Master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
    ports:
      - 4040:4040
      - 6066:6066
      - 8080:8080
      - 18080:18080
    volumes:
      - ./conf/spark-master:/conf
      - ./data:/tmp/data
      - ./shared:/shared

  spark-worker:
    deploy:
      replicas: 1
    image: local/spark-2
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    volumes:
      - ./conf/spark-worker-1:/conf
      - ./data:/tmp/data
      - ./shared:/shared  
