#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/lib.sh
start-hadoop-datanode 2>&1 | collect_stdout datanode &
spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 2>&1 | collect_stdout spark-worker &
set +o xtrace
while /bin/true; do
    sleep 60000
    check_running start-hadoop-datanode
    check_running org.apache.spark.deploy.worker.Worker
done
