#!/bin/bash
set -x
function check_start {
    if [ $1 -ne 0 ]; then
        echo "Failed to start $2: $1"
        exit $1
    fi
}

function check_running {
    ps aux | grep $1 | grep -q -v grep
    status=$?
    if [ $status -ne 0 ]; then
        echo "$1 stopped. Terminating"
        exit $status
    fi
}

function collect_stdout {
    #sed -e '/^$/d' |  jq -R . | sed -e 's/^/{"'"$1"'":/' -e 's/$/}/' | stdbuf -oL fluent-bit -f 10 -v -i stdin -o forward://fluentd:24224
    logger --rfc5424 -n fluentd -P 5140 -t $1
}

hostname=`hostname`
start-hadoop-namenode 2>&1 | collect_stdout &
check_start $? start-hadoop-namenode

spark-class org.apache.spark.deploy.master.Master 2>&1 | collect_stdout &
check_start $? spark-master

while /bin/true; do
    sleep 60
    check_running start-hadoop-namenode
    check_running org.apache.spark.deploy.master.Master
done
