#!/usr/bin/env bash
set -x

# Repalce namenode host in core-site.xml, since docker service name cannot be used as hostname when listening in docker stack setup
# sed -i.bak "s|namenode|$(hostname)|g" $HADOOP_CONF_DIR/core-site.xml
# rm -f $HADOOP_CONF_DIR/core-site.xml.bak

# Format namenode
if [ ! -f $HDFS_VOL1/name/current/VERSION ]; then
    hdfs namenode -format -force
fi

# start namenode process
hdfs namenode
