#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/lib.sh
start-hadoop-namenode 2>&1 | collect_stdout namenode &
check_start $? start-hadoop-namenode

spark-class org.apache.spark.deploy.master.Master 2>&1 | collect_stdout spark-master &
check_start $? spark-master
set +o xtrace
while /bin/true; do
    sleep 600000
    check_running start-hadoop-namenode
    check_running org.apache.spark.deploy.master.Master
done
